### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by zeke** [hokein/electron-screen-recorder#2]
When I run `electron-screen-recorder`, the Electron icon appears in the dock, but there is no application window, no menubar icon... nothing is happening from what I can tell. Am I doing it wrong?

```
❯ uname -a
Darwin C02R41WSFVH8 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64

❯ node -v
v7.2.1

❯ npm -v
3.10.10
```

**Comment by hokein** [comment]
@zeke Thanks for the report, it should work now. You can install the latest version via `npm install`.
